import React from 'react';
import './InnerPages.css';
import { Link } from 'react-router-dom';

const WhatIsJS = () => {
    return (
        <div className='javascript'>
            <div className='content'>
                <div className='side_bar'>
                    <Link className='link'><div>What is JavaScript ?</div></Link>
                    <Link className='link' to={'/closure'}><div>What is Closure ?</div></Link>
                    <Link className='link' to={'/function'}><div>What is Function ?</div></Link>
                    <Link className='link' to={'/variables'}><div>What are Variables ?</div></Link>
                    <Link className='link' to={'/hoisting'}><div>What is Hoisting ?</div></Link>
                </div>
                <div className='inner_content1'>
                    <h2>What is JavaScript ?</h2><hr />
                    <p>
                        Javascript is a dynamic computer programming language. It is lightweight and most
                        commonly used as a part of web pages, whose implementations allow client-side
                        script to interact with the user and make dynamic pages. It is an interpreted
                        programming language with object-oriented capabilities.
                        JavaScript was first known as LiveScript, but Netscape changed its name to
                        JavaScript, possibly because of the excitement being generated by Java. JavaScript
                        made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. <br /><br />The
                        general-purpose core of the language has been embedded in Netscape, Internet
                        Explorer, and other web browsers.
                        The ECMA-262 Specification defined a standard version of the core JavaScript
                        language.<br /><br />
                        &bull; JavaScript is a lightweight, interpreted programming language.<br /><br />
                        &bull; Designed for creating network-centric applications.<br /><br />
                        &bull; Complementary to and integrated with Java.<br /><br />
                        &bull; Complementary to and integrated with HTML.<br /><br />
                        &bull; Open and cross-platform.<br /><br />
                    </p>
                </div>
            </div>
        </div>
    )
}

export default WhatIsJS;